<?php

$config = [
	'name' => __('Danh mục sản phẩm', 'blocksy-child'),
	'clone' => false,
	'devices' => ['desktop'],
	'selective_refresh' => [
		'menu_heading',
		'menu_columns',
		'link_1_label',
		'link_1_url',
		'link_2_label',
		'link_2_url',
		'link_3_label',
		'link_3_url',
		'link_4_label',
		'link_4_url',
		'link_5_label',
		'link_5_url',
		'link_6_label',
		'link_6_url',
		'link_7_label',
		'link_7_url',
		'link_8_label',
		'link_8_url',
	],
	'translation_keys' => [
		['key' => 'menu_heading'],
		['key' => 'link_1_label'],
		['key' => 'link_2_label'],
		['key' => 'link_3_label'],
		['key' => 'link_4_label'],
		['key' => 'link_5_label'],
		['key' => 'link_6_label'],
		['key' => 'link_7_label'],
		['key' => 'link_8_label'],
	],
];
